- name: instalando Repositorio - Ubuntu
  apt:
    deb: /root/puppet6-release-xenial.deb
    state: present

- name: Instalando o puppet-agent - Ubuntu
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
