- name: Parando HTTPD - RED HAT
  service:
    name: httpd
    state: stopped
  ignore_errors: True
  when: ansible_os_family == "Redhat"

- name: Removendo HTTPD - RED HAT
  yum:
    name: httpd*
    state: absent
  when: ansible_os_family == "Redhat"
